# Generated by Django 4.2.7 on 2023-11-16 22:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("libs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newslettersubscription",
            name="email",
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="mobile_number",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
