# Generated by Django 4.2.7 on 2023-11-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0002_userreview_timestamp_alter_userreview_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("website", models.TextField()),
                ("rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("verified", models.CharField(max_length=255)),
            ],
        ),
    ]
