# Generated by Django 4.2.7 on 2023-11-03 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0003_broker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreview",
            name="broker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="broker.broker"
            ),
        ),
    ]
