# Generated by Django 4.2.7 on 2023-11-14 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="time_stamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
