# Generated by Django 4.2.7 on 2023-11-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0002_commodity_time_stamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommodityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="commodity_images/")),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="bids.commodity",
                    ),
                ),
            ],
        ),
    ]
