# Generated by Django 4.2.7 on 2023-11-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0004_alter_userreview_broker"),
        ("bids", "0003_commodityimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="broker",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="broker.broker",
            ),
            preserve_default=False,
        ),
    ]
