# Generated by Django 4.2.7 on 2023-11-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0004_commodity_broker"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodityimage",
            name="broker",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bids.commodity",
            ),
            preserve_default=False,
        ),
    ]
