# Generated by Django 4.2.7 on 2023-11-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0004_alter_userreview_broker"),
        ("bids", "0005_commodityimage_broker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodityimage",
            name="broker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="broker.broker"
            ),
        ),
    ]
