# Generated by Django 4.2.7 on 2023-11-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodity", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="productType",
            new_name="commodityType",
        ),
        migrations.RenameField(
            model_name="commodity",
            old_name="productType",
            new_name="commodityType",
        ),
    ]
