# Generated by Django 4.2.7 on 2023-11-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodity", "0002_rename_producttype_commoditytype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
