# Generated by Django 4.2.7 on 2023-11-03 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commodity", "0004_commodity_market"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commodity",
            name="market",
        ),
        migrations.AddField(
            model_name="priceentry",
            name="market",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commodities",
                to="commodity.market",
            ),
        ),
    ]
