# Generated by Django 4.2.7 on 2023-11-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "commodity",
            "0006_commodity_unit_of_measurement_priceentry_quantity_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commodity",
            name="unit_of_measurement",
        ),
        migrations.RemoveField(
            model_name="priceentry",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="priceentry",
            name="market",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commodities",
                to="commodity.market",
            ),
        ),
    ]
